CRUD_Solution/Models/ContactModel.cs
using CRUD_ClassLibrary.GlobalResource;
using CRUD_Solution.CommonHelper;
using System.ComponentModel.DataAnnotations;
using System.Web;
using System.Web.Mvc;

namespace CRUD_Solution.Models
{
    public class ContactModel
    {
        public int ID { get; set; }
        [Required(ErrorMessageResourceName = WebConstant.ERROR_FIRSTNAME, ErrorMessageResourceType = typeof(MessageResource))]
        [Display(Name = WebConstant.FIRSTNAME, ResourceType = typeof(StringResource))]
        public string FirstName { get; set; }
        [Required(ErrorMessageResourceName = WebConstant.ERROR_LASTNAME, ErrorMessageResourceType = typeof(MessageResource))]
        [Display(Name = WebConstant.LASTNAME, ResourceType = typeof(StringResource))]
        public string LastName { get; set; }
        [Required(ErrorMessageResourceName = WebConstant.ERROR_EMAIL, ErrorMessageResourceType = typeof(MessageResource))]
        [RegularExpression(WebConstant.REGEX_EMAIL,ErrorMessage = WebConstant.REGEX_EMAIL_MSG)]
        [Display(Name = WebConstant.EMAIL, ResourceType = typeof(StringResource))]
        public string Email { get; set; }
        [Required(ErrorMessageResourceName = WebConstant.ERROR_PHONENUMBER, ErrorMessageResourceType = typeof(MessageResource))]
        [RegularExpression(WebConstant.REGEX_PHONENUMBER, ErrorMessage =WebConstant.REGEX_PHONENUMBER_MSG)]
        [Display(Name = WebConstant.PHONENUMBER, ResourceType = typeof(StringResource))]
        public string PhoneNumber { get; set; }
        [Required(ErrorMessageResourceName = WebConstant.ERROR_STATUS, ErrorMessageResourceType = typeof(MessageResource))]
        [Display(Name = WebConstant.STATUS, ResourceType = typeof(StringResource))]
        public string Status { get; set; }
    }
}

CRUD_Solution/Controllers/ContactController.cs
using CRUD_Api.Models;
using CRUD_ClassLibrary.ClassLibrary;
using CRUD_ClassLibrary.ExceptionLogger;
using CRUD_DAL.DataLayer;
using CRUD_Solution.CommonHelper;
using CRUD_Solution.Models;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace CRUD_Solution.Controllers
{
    public class ContactController : Controller
    {
        [HttpGet]
        public ActionResult Add()
        {
            try
            {
                BindDropDown();
                return View();
            }
            catch (Exception ex)
            {
                Logger.ExpectionLogger(ex, "Add Get");
                return RedirectToAction("Error", "Error");
            }
        }
        [HttpPost]
        public async Task<ActionResult> Add(ContactModel contactModelObj)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    ContactRequest contactRequestObj = new ContactRequest
                    {
                        FirstName = contactModelObj.FirstName,
                        LastName = contactModelObj.LastName,
                        Email = contactModelObj.Email,
                        PhoneNumber = contactModelObj.PhoneNumber,
                        Status = contactModelObj.Status,
                        ID = 1
                    };
                    await HelperClass.PushContactDetails(contactRequestObj);
                }
                else
                {
                    return RedirectToAction("Error", "Error");
                }
                return RedirectToAction("GetContacts");
            }
            catch (Exception ex)
            {
                Logger.ExpectionLogger(ex, "Add Post");
                return RedirectToAction("Error", "Error");
            }
        }
        [HttpGet]
        public async Task<ActionResult> GetContacts()
        {
            try
            {
                IList<ContactResponse> contactResponseListObj = null;
                contactResponseListObj = await HelperClass.GetContactDetails();
                return View(contactResponseListObj);
            }
            catch (Exception ex)
            {
                Logger.ExpectionLogger(ex, "GetContacts");
                return RedirectToAction("Error", "Error");
            }
        }
        [HttpGet]
        public async Task<ActionResult> EditContact(int ID)
        {
            try
            {
                BindDropDown();
                List<ContactResponse> contactResponseListObj = new List<ContactResponse>();
                contactResponseListObj = await HelperClass.GetOneContactDetails(ID);
                ContactModel contactModelObj = new ContactModel
                {
                    FirstName = contactResponseListObj[0].FirstName,
                    LastName = contactResponseListObj[0].LastName,
                    Email = contactResponseListObj[0].Email,
                    PhoneNumber = contactResponseListObj[0].PhoneNumber,
                    Status = contactResponseListObj[0].Status,
                    ID = int.Parse(contactResponseListObj[0].ID)
                };
                return View("UpdateContact", contactModelObj);
            }
            catch (Exception ex)
            {
                Logger.ExpectionLogger(ex, "EditContact Get");
                return RedirectToAction("Error", "Error");
            }
        }
        [HttpPost]
        public async Task<ActionResult> EditContact(ContactModel contactModelObj)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    ContactRequest contactRequestObj = new ContactRequest
                    {
                        ID = contactModelObj.ID,
                        FirstName = contactModelObj.FirstName,
                        LastName = contactModelObj.LastName,
                        Email = contactModelObj.Email,
                        PhoneNumber = contactModelObj.PhoneNumber,
                        Status = contactModelObj.Status
                    };
                    await HelperClass.UpdateOneContactDetails(contactRequestObj);
                }
                else
                {
                    return RedirectToAction("Error", "Error");
                }
                return RedirectToAction("GetContacts");
            }
            catch (Exception ex)
            {
                Logger.ExpectionLogger(ex, "EditContact Post");
                return RedirectToAction("Error", "Error");
            }
        }
        [HttpGet]
        public async Task<ActionResult> DeletContacts(int ID)
        {
            try
            {
                await HelperClass.DeleteContact(ID);
                return RedirectToAction("GetContacts");
            }
            catch (Exception ex)
            {
                Logger.ExpectionLogger(ex, "DeletContacts");
                return RedirectToAction("Error", "Error");
            }
        }
        [NonAction]
        public void BindDropDown()
        {
            try
            {
                List<StatusResponse> statusResponseListObj = new List<StatusResponse>();
                statusResponseListObj = Status_DAL.GetStatus();
                ViewBag.StatusList = new SelectList(statusResponseListObj, "ID", "STATUS");
            }
            catch (Exception ex)
            {
                Logger.ExpectionLogger(ex, "DeletContacts");
            }
        }
    }
}

CRUD_Solution/Controllers/DevProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CRUD_Solution.Controllers
{
    public class DevProfileController : Controller
    {
        // GET: DevProfile
        [HttpGet]
        public ActionResult MyProfile()
        {
            return View();
        }
    }
}

CRUD_Solution/Controllers/ErrorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CRUD_Solution.Controllers
{
    public class ErrorController : Controller
    {
        // GET: Error
        public ActionResult Error()
        {
            return View();
        }
    }
}

CRUD_Solution/Views/Contact/Add.cshtml
@model CRUD_Solution.Models.ContactModel

@{
    ViewBag.Title = "Add Contact";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Contact Us</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control"} })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Status, (SelectList)ViewBag.StatusList, new { @class = "dropdown",@id = "ddlStatus" })
                @*@Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })*@
                <span id="ddlError"></span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit" id="btnSubmit" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

CRUD_Solution/Views/Contact/GetContacts.cshtml
@model IEnumerable<CRUD_Api.Models.ContactResponse>

@{
    ViewBag.Title = "View Contact List";
}
<p>
    @Html.ActionLink("Create New", "Add", "Contact")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PhoneNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Status)
        </td>
        <td>
            @Html.ActionLink("Edit", "EditContact", new { id=item.ID }) |
            @Html.ActionLink("Delete", "DeletContacts", new { id=item.ID })
        </td>
    </tr>
}

</table>

CRUD_Solution/Views/Contact/UpdateContact.cshtml
@model CRUD_Solution.Models.ContactModel

@{
    ViewBag.Title = "Update Contact";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Update Contact</h4>
        <hr />
        <div>
            @Html.ActionLink("Back to View Contact", "GetContacts")
        </div>
        <br />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Status, (SelectList)ViewBag.StatusList, new { @class = "dropdown",@id="ddlStatus" })
                @*@Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })*@
                <span id="ddlError"></span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Update" id="btnSubmit" class="btn btn-default" />
            </div>
        </div>
    </div>
}



<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

CRUD_Solution/Views/DevProfile/MyProfile.cshtml
@{
    ViewBag.Title = "My Profile";
}

<img src="~/Content/images/MyPic.gif" /><br /><br />
<p>
    <b>
        Kunal Brahme |
        Contact No. : +91 7507305390 |
        Email ID: kunalbrahme121@gmail.com
    </b>
</p>

<p> <b>Summary</b></p>

<p>
    <ul>
        <li>
            Overall 4.2 years of Rich experience in all phases of Software Development Life Cycle (SDLC) and Software Maintenance Life Cycle (SMLC)
            with concentration development and implementation of applications, including requirements gathering, designing,
            detailed client - server / web-based applications specifications, development, testing, and post-implementation support.
        </li>
    </ul>
</p>
<p>
    <ul>
        <li>
            Currently working with fiserv in destination of software development Engineer professional.
        </li>
    </ul>
</p>
<p>
    <ul>
        <li>
            Worked with TCS for about 3.10 years as Asp.net developer.
        </li>
    </ul>
</p>
<p>
    <ul>
        <li>
            Excellent interpersonal and analytical skills and a motivated team player with the ability to work independently.
        </li>
    </ul>
</p>
<p>
    <ul>
        <li>
            Ability to handle multiple tasks, Initiative and Adaptable. Self-motivated and total commitment to the organizational goals.
        </li>
    </ul>
</p>
<p>
    <ul>
        <li>
            Expertise in Microsoft .Net Technologies (ASP.NET MVC, Asp.Net, .Net Framework 3.5, 4.5, Entity framework 5.0, 6.0, C#.Net,
            Visual Studio-2010, 2012, 2015, SQL Server- 2008/2012/2015).
        </li>
    </ul>
</p>
<p>
    <ul>
        <li>
            Experience in SQL Query design, Functions, Stored Procedure, Trigger and View, SQL Profiler, Tuning Advisor etc.
        </li>
    </ul>
</p>
<p>
    <ul>
        <li>
            Experience in using ASP.NET AJAX for quickly creating an efficient and interactive web application that works across all popular browsers.
        </li>
    </ul>
</p>
<p>
    <ul>
        <li>
            Customized many features through JQuery and JS and with heavy DOM manipulation as per the client’s requirement.
        </li>
    </ul>
</p>
<p>
    <ul>
        <li>
            Experience in implementing Asp.MVC application with repository pattern.
        </li>
    </ul>
</p>
<p>
    <ul>
        <li>
            Performed Unit Testing for the piecewise testing of the Applications.
        </li>
    </ul>
</p>

<p>
    <ul>
        <li>
            Expertise in Object Oriented Programming (OOPS) Concepts along with experience in Debugging.
        </li>
    </ul>
</p>
<p>
    <ul>
        <li>
            Knowledge of building solutions with n-Tier Architecture with the latest technology like Angular Js, WebApi.
        </li>
    </ul>
</p>
<p>
    <ul>
        <li>
            Knowledge of migrating existing Asp.Net projects into Asp.Net MVC projects.
        </li>
    </ul>
</p>
<p>
    <ul>
        <li>
            Good knowledge of writing the web services (WCF, WebApi), implementing and consuming into projects.
        </li>
    </ul>
</p>
<p>
    <ul>
        <li>
            Experience in client handling and interaction. Involve in many transitions (handover and takeover) of projects from different companies.
        </li>
    </ul>
</p>
<p>
    <ul>
        <li>
            Good Knowledge of IIS server.</li></ul>
</p>

CRUD_Solution/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Valence Health</title>
    <!-- Bootstrap core CSS -->
    <link href="~/CustomStyle/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <!-- Custom fonts for this template -->
    <link href="~/CustomStyle/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <!-- Plugin CSS -->
    <link href="~/CustomStyle/vendor/magnific-popup/magnific-popup.css" rel="stylesheet" />
    <!-- Custom styles for this template -->
    <link href="~/CustomStyle/StyleSheet/freelancer.css" rel="stylesheet" />
</head>
<body id="page-top">
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg bg-secondary fixed-top text-uppercase" id="mainNav">
        <div class="container">
            <a class="navbar-brand js-scroll-trigger" href="@Url.Action("Add","Contact")" >Valence Health</a>
            <button class="navbar-toggler navbar-toggler-right text-uppercase bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fa fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item mx-0 mx-lg-1">
                        <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="@Url.Action("GetContacts","Contact")" >View Contacts</a>
                    </li>
                    <li class="nav-item mx-0 mx-lg-1">
                        <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="@Url.Action("MyProfile","DevProfile")" >My Portfolio</a>
                    </li>
                    <li class="nav-item mx-0 mx-lg-1">
                        <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="@Url.Action("Add","Contact")" >Contact us</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container bg-primary text-white">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Valence Health</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <!-- Bootstrap core JavaScript -->
    <script src="~/CustomStyle/vendor/jquery/jquery.min.js"></script>
    <script src="~/CustomStyle/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- Plugin JavaScript -->
    <script src="~/CustomStyle/vendor/jquery-easing/jquery.easing.min.js"></script>
    <script src="~/CustomStyle/vendor/magnific-popup/jquery.magnific-popup.min.js"></script>
    <!-- JS Validation -->
    <script src="~/CustomStyle/Js/jsValidation.js"></script>
</body>
</html>